# Generated by Django 4.2.6 on 2023-10-29 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daftar_buku', '0004_rating_alter_buku_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='daftar_buku.buku')),
            ],
        ),
    ]
