# Generated by Django 4.2.6 on 2023-10-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('star_count', models.PositiveSmallIntegerField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
