# Generated by Django 4.2.6 on 2023-10-26 15:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daftar_buku', '0002_alter_buku_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_dipinjam', models.DateField(auto_now_add=True)),
                ('tanggal_pengembalian', models.DateField(default=django.db.models.expressions.CombinedExpression(models.F('tanggal_dipinjam'), '+', models.Value(datetime.timedelta(days=3))))),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daftar_buku.buku')),
                ('peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
