# Generated by Django 4.2.6 on 2023-10-29 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daftar_buku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengembalian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBuku', models.IntegerField()),
                ('review', models.BooleanField(default=False)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daftar_buku.buku')),
                ('peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBuku', models.IntegerField()),
                ('tanggal_dipinjam', models.DateField(auto_now_add=True)),
                ('hari', models.IntegerField(blank=True, null=True)),
                ('tanggal_pengembalian', models.DateField(blank=True, null=True)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daftar_buku.buku')),
                ('peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
