# Generated by Django 4.2.6 on 2023-10-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam_buku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='hari',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal_pengembalian',
            field=models.DateField(blank=True, null=True),
        ),
    ]
