# Generated by Django 4.2.6 on 2023-10-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam_buku', '0002_peminjaman_hari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='idBuku',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
