# Generated by Django 4.2.6 on 2023-10-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam_buku', '0003_peminjaman_idbuku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='hari',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
