# Generated by Django 4.2.6 on 2023-10-28 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_buku', '0002_alter_buku_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinjam_buku', '0004_alter_peminjaman_hari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengembalian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBuku', models.IntegerField()),
                ('review', models.BooleanField(default=False)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daftar_buku.buku')),
                ('peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
