# Generated by Django 4.2.6 on 2023-10-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_buku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='rating',
            field=models.FloatField(),
        ),
    ]
