# Generated by Django 4.2.6 on 2023-10-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_buku', '0002_alter_buku_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
