# Generated by Django 4.2.6 on 2023-10-27 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_buku', '0003_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='buku',
            name='rating',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='daftar_buku.rating'),
        ),
    ]
