# Generated by Django 4.2.6 on 2023-10-29 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daftar_buku', '0004_rating_alter_buku_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20)),
                ('judul', models.CharField(max_length=100)),
                ('penulis', models.CharField(max_length=100)),
                ('tahun', models.IntegerField()),
                ('kategori', models.CharField(max_length=100)),
                ('gambar', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('rating', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='daftar_buku.rating')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
