# Generated by Django 4.2.6 on 2023-10-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication_bookmark', '0003_alter_customuser_options_alter_bookmark_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
