# Generated by Django 4.2.6 on 2023-10-28 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_buku', '0002_alter_buku_rating'),
        ('authentication_bookmark', '0005_rename_user_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='gambar',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='buku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daftar_buku.buku'),
        ),
    ]
